### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#1]
- [x]  $watch
finished in [0.1.3](https://github.com/Chimeejs/chimee/releases/tag/0.1.3)
- [x] width and height of video should support percentage (support in [0.2.0](https://github.com/Chimeejs/chimee/releases/tag/0.2.0)
- [x] add `isFullScreen` on video to tell plugin the fullscreen state, or make fullscreen pass by event (support in [0.2.0](https://github.com/Chimeejs/chimee/releases/tag/0.2.0))
- [x] support offsetHeight, offsetWidth etc (support in [0.2.0](https://github.com/Chimeejs/chimee/releases/tag/0.2.0))
- [x] support error on video (support in [0.2.0](https://github.com/Chimeejs/chimee/releases/tag/0.2.0))
- [x] support silent load (support in [0.2.0](https://github.com/Chimeejs/chimee/releases/tag/0.2.0))
Developer may want to support multi-clarity. If they change clarity by loading a new src. That is slow. So it may be a good idea to support silent load and change the video when loading is finished.
- [x] load new src including box change (support in [0.2.0](https://github.com/Chimeejs/chimee/releases/tag/0.2.0))
As in silent load we can change box and kernel, we can also support change box on load too
- [x] custom kernel  (support in [0.2.0](https://github.com/Chimeejs/chimee/releases/tag/0.2.0))
user can choose the kernel. In that way, we can reduce our code size.
- [x] add some css guide on document and think about what should we do on css
- [x] throw plugin name
- [x] fix `plugins` and `plugin` error on document or support both
- [x] fix fullscreen on IE9-IE10 (fixed in [0.2.8](https://github.com/Chimeejs/chimee/releases/tag/0.2.8))
- [x] add fullscreen event on chimee (fixed in [0.2.8](https://github.com/Chimeejs/chimee/releases/tag/0.2.8))
- [x] fix load empty bug on non-autoload mode (fixed  in [0.2.8](https://github.com/Chimeejs/chimee/releases/tag/0.2.8))
- [x] silentload events
- [x] support static preset install (will be landed on 0.4.0)
- [x] add autoload tips on demo
when people haven't pass src but mark with autoload, we should offer a tips
- [x] use babel-env to build
- [ ] english document and guidance
- [ ] environment test
offer a method like isSupport to let user know whether the kernel is supported in this environment.
- [ ] check preset and kernels on chimee layer
mostly check with box setting, but this is basically job of kernel

----- discussion

- [ ] weex
- [ ] chimee with pwa
- [ ] debug mode and code minify
- [ ] 小程序
support better debug experience and minify debug code

**Comment by toxic-johann** [comment]
**How to switch video clarity?**
In fact, we try to create a new muted invisible video, and load the src of different clarity. When we finish loading, we replace the old video with this one.

Assume the old video is `v0`, old kernel is `k0`, old src is `s0`.
So the new video is `v1`, new kernel is `k1`, new src is `s1`.
We will switch in `n` second.
We call the switch event `silentLoad`, load a src quietly.

We will offer a function called `silentLoad`. When you call it, we will follow the steps below:
1. We create a `Promise` and return it
2. We emit an event called `silentLoad`
3. If a plugin stop the event in `beforeSlilentLoad`, we will reject the `Promise`, then finished.
4. else we run into `silentLoad` processor
5. we create an config object `c1` like this
```javascript
{
  src: s1,
  box: currentBox,
  isLive: currentState
}
```
6. we create new video elemnt `v1`, we set it muted and invisible
7. we create a new kernel `k1` with `v1` and `c1`
8. we load `s1` on `k1`
9. we seek to currentTime + `n`
10. If we could not seek successfully in `n` second, we trigger `silentLoad` and pass arguments for failed. Finally, we reject the `Promise`.
11. If we seek successfully in `n` second, we wait until the time.
12. we destroy the old kernel `k0`, and remove `v0`
13. we append `v1` in the `container`.
14. we attach `k1` on `dipatcher`.
15. we trigger `silentLoad` and pass arguments

**Comment by toxic-johann** [comment]
If you have any new idea about chimee. Please leave under this issue. We will consider it seriously.

**Comment by toxic-johann** [comment]
move to this issue https://github.com/Chimeejs/chimee/issues/119
