### ISSUE TITLE
ROADMAP to 1.0

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#119]
We plan to published 1.0 in this year. And this issue,  we will update our process of development. And we will list the feature we want to support below. Everyone is welcome to join in the discuss.

The major features of 1.0.
- [ ] new event system (will be landed in 0.10.0) https://github.com/Chimeejs/chimee/issues/106
- [ ] chimee-plugin-canvas-render (will be published with 0.10.0) https://github.com/Chimeejs/chimee/issues/96
- [ ] chimee-plugin-panorama (will be published with 0.10.0) https://github.com/Chimeejs/chimee/issues/66
- [ ] support container remove option
- [ ] replace custom helper with lodash (will be landed in 0.11.0)
- [ ] replace flow-js with typescript (will be landed in 0.12.0)
- [ ] chimee-devtool
- [ ] english document

**Comment by falost** [comment]
希望尽快支持 typescript 吧
