### ISSUE TITLE
Embedded canvas rendering layer ROADMAP

### ISSUE THREAD

**Issue by toxic-johann** [Chimeejs/chimee#96]
要实现类似[https://github.com/Chimeejs/chimee/issues/66](https://github.com/Chimeejs/chimee/issues/66)中的需求，我们需要增加内嵌的 canvas 渲染层。因此有如下工作需要完成。

To meet the requirements in [https://github.com/Chimeejs/chimee/issues/66](https://github.com/Chimeejs/chimee/issues/66), we need to add an embedded canvas rendering layer. The following work is therefore required

- [x] 实现内嵌的 canvas 层，与 video 同级别，用于过渡上层操作。 Realize the embedded canvas layer, at the same level as video, for transition upper level operations
- [x] 实现 video 帧轮询接口（可拓展）Implementation of video frame polling interface(extendable)
- [x] 实现 canvas 绘制接口（可拓展）Implement canvas rendering interface(extendable)
